# Generated by Django 5.0.6 on 2024-05-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_rename_post_posts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="posts",
            old_name="created_at",
            new_name="created",
        ),
    ]
