# Generated by Django 5.0.6 on 2024-05-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_rename_created_at_posts_created"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Posts",
            new_name="Post",
        ),
    ]
