# Generated by Django 5.0.6 on 2024-05-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("detail", models.TextField()),
                ("status", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
