# Generated by Django 5.0.6 on 2024-06-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="narration",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
